
version: "3.9"
services:
  inklink:
    build:
      context: .
      dockerfile: Dockerfile

    # Map HTTP server port for external access
    ports:
      - "9999:9999"

    # Run the InkLink HTTP server by default
    command: ["poetry", "run", "inklink", "server", "--host", "0.0.0.0", "--port", "9999"]
    environment:
      - PYTHONUNBUFFERED=1
      - LIMITLESS_API_KEY=${LIMITLESS_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASS=${NEO4J_PASS}
      - MYSCRIPT_APP_KEY=${MYSCRIPT_APP_KEY}
      - MYSCRIPT_HMAC_KEY=${MYSCRIPT_HMAC_KEY}
      - RMAPI_PATH=/usr/local/bin/rmapi
      - DRAWJ2D_PATH=/usr/bin/drawj2d
      - REMARKABLE_DIR=/tmp/remarkable_output
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ${HOME}/.config/rmapi:/root/.config/rmapi
      - /tmp/remarkable_output:/tmp/remarkable_output

  # FastAPI backend for syntax highlighting
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["uvicorn", "inklink.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - PYTHONUNBUFFERED=1
      - MYSCRIPT_APP_KEY=${MYSCRIPT_APP_KEY}
      - MYSCRIPT_HMAC_KEY=${MYSCRIPT_HMAC_KEY}
      - RMAPI_PATH=/usr/local/bin/rmapi
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ${HOME}/.config/rmapi:/root/.config/rmapi
      - ./themes:/app/themes

  # Nuxt frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://api:8000
    depends_on:
      - api
