name: Auto Add to Kanban

on:
  workflow_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    # Removed job-level env for GH_TOKEN; set it in the relevant steps instead
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh -y
        # No 'token' input; authentication is handled via GH_TOKEN env in later steps
      - name: Ensure gh-projects extension
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh extension list | grep -q 'github/gh-projects'; then
            gh extension install github/gh-projects
          fi
      - name: Bootstrap Kanban project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/manage_project.sh

      - name: Add new issue/PR to InkLink Kanban
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: rmulligan/remarkable-ink-link
          PROJECT_NAME: InkLink Kanban
        run: |
          # Determine the URL of the new item (issue or PR)
          if [ "${{ github.event_name }}" = "issues" ]; then
            ITEM_URL="${{ github.event.issue.html_url }}"
          else
            ITEM_URL="${{ github.event.pull_request.html_url }}"
          fi
          # Find the project number
          PROJ_NUM=$(gh projects list --repo "$REPO" --json number,name --jq '.[] | select(.name=="'"$PROJECT_NAME"'").number')
          echo "Adding $ITEM_URL to project '$PROJECT_NAME' (number $PROJ_NUM)"
          gh projects item-add "$PROJ_NUM" --repo "$REPO" --url "$ITEM_URL"
